name: Build Component in Native Environment with Tests

on:
  workflow_dispatch:
  # push:
  #   branches: [ main, 'sprint/**', 'release/**', develop ]
  # pull_request:
  #   branches: [ main, 'sprint/**', 'release/**', topic/RDK*, develop ]

jobs:
  build-voicecontrol-on-pr:
    name: Build entservices-voicecontrol component in github rdkcentral
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rdkcentral/docker-rdk-ci:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: build dependencies
        run: |
          sh -x build_dependencies.sh --build-tests
        env:
          GITHUB_TOKEN: ${{ secrets.RDKCM_RDKE }}
          CTRLM_TAG: ${{ vars.CTRLM_TAG }}

      - name: cov build
        run: |
          sh -x cov_build.sh --build-tests
        env:
          GITHUB_TOKEN: ${{ secrets.RDKCM_RDKE }}